### ISSUE TITLE
Adding multiple files inside a folder

### ISSUE THREAD

**Issue by tampeta** [ddliu/node-svn-spawn#10]
Hi!

First of all, thanks for this module it has been quite simple to understand it. However, I ran into a small issue (hopefully it is small :) )

I am trying to implement a scheduled commit (every day) for all log files inside a folder. My problem is that I first have to add all files inside the folder and then commit that folder alone. I tried using the add function and adding /* at the end of the file path as shown below:

```
client.add('LoggingServer/testLogs/*', function(err, data) {

        client.commit(['This is an automatic commit for the log files', 'LoggingServer/testLogs'], function(err, data) {
                console.log('Log files committed!');
        });
});
```

Unfortunately, that does not work and I get this error: 

> svn: warning: W155010: '/Users/silvia/WebstormProjects/miracle/src/LoggingServer/testLogs/*' not found
> svn: E200009: Could not add all targets because some targets don't exist
> svn: E200009: Illegal target for the requested operation
> { [Error: svn: warning: W155010: '/Users/silvia/WebstormProjects/miracle/src/LoggingServer/testLogs/*' not found
> svn: E200009: Could not add all targets because some targets don't exist
> svn: E200009: Illegal target for the requested operation
> ] code: 1, output: '' }

I also checked the addLocal function but that is not an option because I do not want ALL local changes to be added because I only want the files inside that specific folder to be committed periodically.

Thanks a lot in advance. Hopefully someone can help me with this issue.

**Comment by ddliu** [comment]
Please confirm that the target folder exist: `/Users/silvia/WebstormProjects/miracle/src/LoggingServer/testLogs/`

**Comment by tampeta** [comment]
The folder does exist. It has the log files which are created every day, but they are not under version control. So I need to first add all the files to svn and then commit the folder. I guess it would be something like the addLocal but only for the particular testLogs folder. Is that possible?

**Comment by ddliu** [comment]
Wildcard is not supported. 

You can either specify all files you want to add:

```
var files = get_file_list(); // ['log/1.log', 'log/2.log', 'log/3.log']
client.add(files, function(err, data) {
    // done
});
```

 or just force add the parent folder:

```
client.add(['log/', '--force'], function(err, data) {
});
```

We have to use `--force` option here so that we can repeatedly add the same folder.

**Comment by tampeta** [comment]
Thank you so much! The force option works like a charm :) . I had seen it already as a command line instruction but didn't know how to pass it as argument to the add function. Thanks a lot again for everything :)
