### ISSUE TITLE
addlocal error

### ISSUE THREAD

**Issue by owen-hong** [ddliu/node-svn-spawn#11]
hi, I commit [global-201608121735.png,global-201608121735.svg,global-201608121735-svg.png] all three files ,but **'global-201608121735.png'** commit fail ,why?

![image](https://cloud.githubusercontent.com/assets/6466628/17654928/e6fa3438-62da-11e6-883a-e604495e7db5.png)

but I use `client.cmd(['add','dir','--force'], function (err, data) {}` no this problem

**Comment by ddliu** [comment]
SVN will return an error if you add a file which is already under version control without the "--force" option.

**Comment by owen-hong** [comment]
才发现都是中国人，我批量添加了几个文件，但是就单独只有那个文件是每次都会漏提交的，但是用了add接口，加上强制提交就能全部添加，也是奇怪的很

**Comment by ddliu** [comment]
这是svn的特性，已经是版本控制的文件不能用`svn add file`重复add了，会提示 "is already under version control"，除非加上"--force"参数

**Comment by owen-hong** [comment]
确实不是node-svn-spawn模块的问题，并发提交SVN文件就会遇到这个问题，自能通过强制提交才能解决这个问题,感谢解答
