### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by SunboX** [ddliu/node-svn-spawn#6]
Getting this exception:

```
{ [Error: spawn ENOENT] code: 'ENOENT', errno: 'ENOENT', syscall: 'spawn' }
```

**Comment by SunboX** [comment]
Maybe you have to use https://github.com/ForbesLindesay/win-spawn ?

**Comment by ddliu** [comment]
Try typing `svn` in cmd.

It requires the svn command, do you have it installed (there is an option to install this command when installing TortuiseSVN)?

**Comment by SunboX** [comment]
I have installed Tortoise SVN & Command Line Tools

![svn-spawn](https://cloud.githubusercontent.com/assets/83344/6106921/f39df78e-b065-11e4-9ed5-a6ba39fa8b9e.PNG)

**Comment by SunboX** [comment]
This works for me:

```javascript
function cmd_exec(cmd, args, cb_stdout, cb_end) {
	var spawn = require('child_process').spawn,
		child = spawn(cmd, args, { cwd: 'D:/Work/Foo' }),
		me = this;
		
	me.exit = 0;  // Send a cb to set 1 when cmd exits
	child.stdout.on('data', function (data) { cb_stdout(me, data) });
	child.stdout.on('end', function () { cb_end(me) });
}

foo = new cmd_exec('svn', ['log'], 
	function (me, data) { me.stdout += data.toString(); },
	function (me) { me.exit = 1; }
);

function log_console() {
	console.log(foo.stdout);
}

// wait 0.25 seconds and print the output
setTimeout(log_console, 250);
```

**Comment by ddliu** [comment]
Interesting, I have been using this library in several projects under Windows without any problem.

Could you please show me some code so that I can reproduce the issue?

**Comment by omerts** [comment]
I am having the same problem, any solutions?

**Comment by ddliu** [comment]
@omerts , I can not reproduce under Windows XP nor Windows 7, could you please show me your code?

By the way, what's your environment: OS, svn version, nodejs version?

**Comment by omerts** [comment]
@ddliu Thanks for the response.

This is the code (I omitted the real path, username and pass):
````javascript
var SvnClient = require('svn-spawn');
var client = new SvnClient({
    cwd: 'path',
    username: 'username', 
    password: 'pass'
});

// Also tried providing the path to the list cmd
client.cmd(['list'], function(err, data) {            
            console.log(err);
            console.log(data);
        });
````
OS: Windows 7 professional SP1 64bit
SVN: I tried both TortoiseSVN and SlikSVN, in both cases using list cmd from cmd line worked fine.
         Currently using SlikSVN, with the following version: 
```
svn, version 1.8.11-SlikSvn-1.8.11-X64 (SlikSvn/1.8.11) X64
compiled Dec  9 2014, 13:44:31 on x86_64-microsoft-windows6.2.9200
```
Node Version: v0.10.35

**Comment by omerts** [comment]
After updating to Node v0.12.0, the error changed to the following:
````
{ [Error: spawn svn ENOENT]
  code: 'ENOENT',
  errno: 'ENOENT',
  syscall: 'spawn svn',
  path: 'svn' }
undefined
{ [Error] code: -4058, output: '' }
undefined
````

**Comment by omerts** [comment]
Ok I think I found the problem. It looks like it is in the easy-spawn module. 
Specifically in the cmd function, change:
````javascript
var options = this.getOption(),
            program,
            s,
            cwd = options.cwd, // It looks like using the same name causes the error
            outputData = [],
            errorData = [];

        if (typeof options.program === 'string') {
            program = options.program;
        }
        else {
            program = cmd.shift();
        }

        if (typeof cwd === 'string') {
            s = spawn(program, cmd, 
                {
                    cwd: cwd // It looks like using the same name causes the error
                }
            );
        }
        else {
            s = spawn(program, cmd);
        }
````
To:
````javascript
var options = this.getOption(),
            program,
            s,
            currentDir = options.cwd,
            outputData = [],
            errorData = [];

        if (typeof options.program === 'string') {
            program = options.program;
        }
        else {
            program = cmd.shift();
        }

        if (typeof cwd === 'string') {
            s = spawn(program, cmd, 
                {
                    cwd: currentDir
                }
            );
        }
        else {
            s = spawn(program, cmd);
        }
````
Now everything works as expected :)

**Comment by ddliu** [comment]
Could you please try to specify the program path?

```
program: "absolute path to svn.exe"
```

There might be something wrong with spawn under 64bit windows. Have to find a 64bit win7 to reproduce it.

[google search](https://www.google.com/search?q=spawn+ENOENT&oq=spawn++ENOENT&aqs=chrome..69i57j69i60.4160j0j7&sourceid=chrome&es_sm=93&ie=UTF-8#newwindow=1&safe=strict&q=spawn+ENOENT+windows+64)

**Comment by omerts** [comment]
@ddliu, it ended up being that I was using a remote directory as my current working directory (cwd), figures spawn cmd doesn't work with it.

**Comment by ddliu** [comment]
@omerts, yes cwd is path of your *local* working directory. Will update document later to make it clear.

**Comment by zombinary** [comment]
rerun TortoiseSVN-1.9.7.27907-x64-svn-1.9.7.msi and install the command line tool only,
fix the problem.

node -v --> 8.9.4 | npm -v --> 5.6.7 | win7 64bit
