### ISSUE TITLE
Should throw error if `svn` CLI is not installed

### ISSUE THREAD

**Issue by gyandeeps** [ddliu/node-svn-spawn#7]
I think it should make sense to throw an error if the `svn cli` is not installed rather than silently exiting.

**Comment by ddliu** [comment]
It should throw an `ENOENT` error in this case, could you please show me your code?

**Comment by gyandeeps** [comment]
I figured it out. So what happens is that it does throw an error if you dont have svn installed on your machine. But when you install svn using tortise on your windows machine the svn CLI is by default not installed. Thats the time it doesnt throw an error and also doesnt work.
Basically you have to have svn CLi installed too.

**Comment by ddliu** [comment]
I've tried to remove TortoiseSVN and reinstall it without SVN CLI, and still got the 'ENOENT' error.
